version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: fw-id-agent
    binary: fw-id-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/fw-id-agent/main.go
    ldflags:
      - -s -w -X github.com/telekom-mms/fw-id-agent/internal/agent.Version={{.Version}}-{{.Commit}}
  - id: fw-id-cli
    binary: fw-id-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/fw-id-cli/main.go
    ldflags:
      - -s -w -X github.com/telekom-mms/fw-id-agent/internal/agent.Version={{.Version}}-{{.Commit}}
archives:
  - formats:
      - tar.gz
    wrap_in_directory: true
    files:
      - src: init/fw-id-agent.service
        dst: fw-id-agent.service
        info:
          mode: 0644
      - src: configs/config.json
        dst: example_config.json
        info:
          mode: 0644
      - README.md
      - LICENSE
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-n{{ .Timestamp }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
nfpms:
  - package_name: fw-id-agent
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    vendor: Deutsche Telekom MMS GmbH
    maintainer: The MMS Linux Dev Team <mmslinux-dev@t-systems-mms.com>
    description: |-
      Firewall Identity Agent
      Agent to log on to the corporate firewall.
    license: MIT
    builds:
      - "fw-id-agent"
      - "fw-id-cli"
    formats:
      - deb
    bindir: /usr/bin
    section: net
    # important: this makes the package non native
    release: "1"
    priority: important
    # chglog init -> generates changelog.yml
    # chglog add --version v#.#.# -> after every tag, call in hook above?
    # activate if https://github.com/goreleaser/nfpm/pull/656 is merged and used in goreleaser
    # -> remove overrides
    # changelog: "changelog.yml"
    scripts:
      postinstall: build/package/postinstall.sh
      postremove: build/package/postremove.sh
    dependencies:
      - "init-system-helpers (>= 1.62)"
    deb:
      lintian_overrides:
        - "no-manual-page"
        - "no-changelog"
        - "statically-linked-binary"
        - "maintainer-script-calls-systemctl"
    contents:
      - src: init/fw-id-agent.service
        dst: /usr/lib/systemd/user/
        file_info:
          mode: 0644
      - src: configs/config.json
        dst: /usr/share/doc/fw-id-agent/examples/
        file_info:
          mode: 0644
      - src: copyright
        dst: /usr/share/doc/fw-id-agent/
        file_info:
          mode: 0644
      - src: README.md
        dst: /usr/share/doc/fw-id-agent/
        file_info:
          mode: 0644
      - src: LICENSE
        dst: /usr/share/doc/fw-id-agent/
        file_info:
          mode: 0644
release:
  prerelease: auto
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
